### ISSUE TITLE
numpy.linalg.LinAlgError: Internal Error.

### ISSUE THREAD

**Issue by byerose** [kai-wen-yang/CD-VAE#9]
I'm reproducing the detection of the paper.
After running `python ADV_Generate_Mahalanobis_Subspace.py --dataset cifar10 --net_type resnet --adv_type PGD --gpu 0 --outf ./data/cd-vae-1/ --vae_path ../pretrained/cd-vae-1.pth;`, some error as follows:
```
Traceback (most recent call last):
  File "ADV_Generate_Mahalanobis_Subspace.py", line 131, in <module>
    main()
  File "ADV_Generate_Mahalanobis_Subspace.py", line 79, in main
    sample_mean, precision = lib_generation.sample_estimator(model, vae, args.num_classes, feature_list, train_loader)
  File "/work/CD-VAE/detection/lib_generation.py", line 117, in sample_estimator
    group_lasso.fit(X.cpu().numpy())
  File "/home/amk/anaconda3/envs/detector/lib/python3.7/site-packages/sklearn/covariance/_empirical_covariance.py", line 212, in fit
    self._set_covariance(covariance)
  File "/home/amk/anaconda3/envs/detector/lib/python3.7/site-packages/sklearn/covariance/_empirical_covariance.py", line 170, in _set_covariance
    self.precision_ = linalg.pinvh(covariance, check_finite=False)
  File "/home/amk/anaconda3/envs/detector/lib/python3.7/site-packages/scipy/linalg/basic.py", line 1450, in pinvh
    s, u = decomp.eigh(a, lower=lower, check_finite=False)
  File "/home/amk/anaconda3/envs/detector/lib/python3.7/site-packages/scipy/linalg/decomp.py", line 604, in eigh
    raise LinAlgError(msg)
numpy.linalg.LinAlgError: Internal Error.
```

**Comment by byerose** [comment]
Using `numpy==1.21.6`
